#!/bin/sh

# Copyright 2016 Antonio Malcolm, released under an MPL, v. 2.0, license. All rights reserved.
#
# This file is part of Corgi Scripts (also referred to as corgi-scripts).
#
# Corgi Scripts is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# you can obtain one at http://mozilla.org/MPL/2.0/.
#
# Corgi Scripts is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either expressed or implied.
# See LICENSE.txt, for the specific language governing rights and limitations under the License,
# which should have been provided with this software, or visit http://mozilla.org/MPL/2.0/.

# corgi-audio-management.shlib - handles management of audio features, such as volume and muting
#
# v2016.04.11
#
# Authored by Antonio Malcolm
#
# 
# Requires: corgi-audio-management.shlib


currentDirectory="`dirname "$0"`"
currentDirectory="`cd "$currentDirectory" ; pwd -P `"
parentDirectory="`dirname $currentDirectory`"

corgiAudioManagementLib="$parentDirectory/lib/corgi/corgi-audio-management.shlib"

if [ ! -e "$corgiAudioManagementLib" ]
then
  logger "ERROR (corgi-audio-control): $corgiAudioManagementLib is missing. Exiting..."
  echo "ERROR (corgi-audio-control): $corgiAudioManagementLib is missing. Exiting..."
  exit 1
fi

export XAUTHORITY=/home/$USER/.Xauthority

. "$corgiAudioManagementLib"

setAudio "$@"
