#!/bin/bash
#    bl-help-pipemenu - an Openbox pipemenu for displaying help files
#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

HELP='    bl-help-pipemenu an Openbox Pipe Menu for displaying help files
    It should normally be called from an openbox menu.

Options (usually passed from the menu):
    -h --help   show this message

    If bl-help-pipemenu is called with no options (the usual method),
    it will output an xml openbox pipemenu displaying various help files,
    both online and on the system.
'
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

menuStart
menuSeparator 'Online Help'
menuSeparator
menuItem 'Forum Basic Help & Support' 'chromium "https://forums.bunsenlabs.org/viewforum.php?id=2"'
menuItem 'Scripts, Tutorials & Tips' 'chromium "https://forums.bunsenlabs.org/viewforum.php?id=9"'
menuSubmenu 'DebianWWW' 'Debian'
menuItem 'Debian Documentation' 'chromium "https://www.debian.org/doc/"'
menuItem 'Debian Handbook' 'chromium "https://debian-handbook.info/browse/jessie/"'
menuItem 'Debian Reference' 'chromium "https://www.debian.org/doc/manuals/debian-reference/"'
menuItem 'Wiki' 'chromium "https://wiki.debian.org/"'
menuItem 'Forum' 'chromium "http://forums.debian.net/"'
menuItem 'Package Search' 'chromium "https://www.debian.org/distrib/packages"'
menuItem 'Package Tracker' 'chromium "https://tracker.debian.org/"'
menuItem 'Security Tracker' 'chromium "https://security-tracker.debian.org/tracker/"'
menuSubmenuEnd
menuItem 'Arch Wiki' 'chromium "https://wiki.archlinux.org/index.php/Table_of_contents"'

menuSeparator

menuSubmenu 'OpenboxWWW' 'Openbox'
menuSubmenu 'ObWWW' 'Openbox Website'
menuItem 'Openbox Homepage' 'chromium "http://openbox.org/"'
menuItem 'Openbox Getting Started' 'chromium "http://openbox.org/wiki/Help:Getting_started"'
menuItem 'Openbox Documentation' 'chromium "http://openbox.org/wiki/Help:Contents"'
menuItem 'Openbox FAQs' 'chromium "http://openbox.org/wiki/Help:FAQ"'
menuSubmenuEnd
menuItem 'ArchWiki Openbox Guide' 'chromium "http://wiki.archlinux.org/index.php/Openbox"'
menuItem 'Debian Wiki Openbox Guide' 'chromium "https://wiki.debian.org/Openbox"'
menuItem 'Urukramas Openbox Guide' 'chromium "https://urukrama.wordpress.com/openbox-faq/"'
menuSubmenuEnd

menuSubmenu 'Tint2WWW' 'Tint2'
menuItem 'Tint2 Wiki: FAQ' 'chromium "https://gitlab.com/o9000/tint2/wikis/FAQ"'
menuItem 'Tint2 Wiki: Configuration' 'chromium "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
menuItem 'Tint2 Forum Thread' 'chromium "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
menuItem 'Tint2 man page' 'x-terminal-emulator -T "Tint2 man page" -e man tint2'
menuSubmenuEnd

menuSubmenu 'ConkyWWW' 'Conky'
menuItem 'Conky Wiki' 'chromium "https://github.com/brndnmtthws/conky/wiki"'
menuItem 'Conky Archive' 'chromium "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
menuItem 'Conky man pages' 'x-terminal-emulator -T "Conky man page" -e man conky'
menuSubmenuEnd
menuSeparator

menuSubmenu 'ThemesWWW' 'Theme Resources'
menuItem 'Bunsenlabs on DeviantArt' 'chromium "http://bunsenlabs.deviantart.com/"'
menuItem 'Box-Look.org' 'chromium "http://www.box-look.org"'
menuItem 'gnome-look.org' 'chromium "http://gnome-look.org/"'
menuSubmenuEnd
menuSeparator
menuSeparator 'man pages'
menuItem 'Compositor' 'x-terminal-emulator -T "Compositor man page" -e man compton'
menuItem 'dmenu' 'x-terminal-emulator -T "dmenu man page" -e man dmenu'
menuItem 'gmrun' 'x-terminal-emulator -T "gmrun man page" -e man gmrun'
menuItem 'xrandr' 'x-terminal-emulator -T "xrandr man page" -e man xrandr'

menuSeparator
menuSubmenu 'BLhelp' 'Bunsen Help Files'
menuItem 'How to Edit Menu' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="How to Edit the Menu" --filename="/usr/share/bunsen/docs/helpfile-menu.txt" --width=900 --height=700 --fontname=Monospace'
menuItem 'About Bunsen Alternatives' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="About Bunsen Alternatives" --filename="/usr/share/bunsen/docs/helpfile-bl-alternatives.txt" --width=900 --height=700 --fontname=Monospace'
menuItem 'Conkyzen Help' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="Conkyzen Help" --filename="/usr/share/bunsen/docs/helpfile-conkyzen.txt" --width=900 --height=700 --fontname=Monospace'
menuSubmenuEnd

menuEnd
