#!/bin/bash
#    bl-printing-pipemenu an Openbox pipemenu for configuring printing
#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
#    Copyright (C) 2013 Aleks-Daniel Jakimenko
#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

HELP='    bl-printing-pipemenu an Openbox Pipe Menu for configuring printing
    It should normally be called from an openbox menu.

Options (usually passed from the menu):
    -h --help   show this message
    --install   install printing support

    If bl-printing-pipemenu is called with no options (the usual method),
    it will output an xml openbox pipemenu
    for installing printing support and configuring printing.
'
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

if [[ $1 = '--install' ]]; then

    terminalCheck -T 'Install Printer Support' --install

    promptInstall 'PRINTING SUPPORT' 'This script will install printing support.' 'bunsen-meta-printer-support'

elif [[ $1 ]]; then
    echo "$0: no such option $*" >&2
    exit 1

else
    # Pipemenu
    menuStart
    if type 'system-config-printer' &> /dev/null; then
        menuItem 'Configure Printers' 'gksudo system-config-printer'
    else
        menuItem 'Install Printing Support' "$0 --install"
    fi
    menuEnd
fi
exit 0
