#!/bin/bash
# ---------------------------------------------------------------------
# Pipemenu to install remote desktop software on Bunsen Labs Linux.
# Originally written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
# ---------------------------------------------------------------------
#    bl-remote-desktop-pipemenu - pipemenu to install remote desktop software
#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
#    Copyright (C) 2013 Aleks-Daniel Jakimenko
#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

HELP='    bl-remote-desktop-pipemenu an Openbox Pipe Menu
    to install remote desktop software
    It should normally be called from an openbox menu.

Options (usually passed from the menu):
    -h --help                   show this message
    --install   viewer|server   install VNC software

    If bl-remote-desktop-pipemenu is called with no options (the usual method),
    it will output an xml openbox pipemenu
    for installing and using remote desktop software.
'
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

if [[ $1 = --install ]]; then
    case $2 in
    viewer)
        terminalCheck -T "Install VNC Viewer" "$@"
        promptInstall 'REMOTE DESKTOP CLIENT' 'This script will install TightVNC Viewer.' 'xtightvncviewer'
        ;;
    server)
        terminalCheck -T "Install VNC Server" "$@"
        promptInstall  'REMOTE DESKTOP SERVER' 'This script will install Vino VNC server and dconf-editor.' 'vino' 'dconf-editor'
        ;;
    *)
        echo "$0: no such install option $2"
        exit 1
        ;;
    esac

elif [[ $1 ]]; then
    echo "$0: no such option $*" >&2
    exit 1

else
    # Pipemenu
    menuStart

    # Viewer
    if type 'xtightvncviewer' &> /dev/null; then
        menuItem 'Viewer' 'vncviewer'
    else
        menuItem 'Install Viewer' "$0 --install viewer"
    fi

    menuSeparator

    # Server
    if [[ -x /usr/lib/vino/vino-server ]]; then
        if pidof -s vino-server > /dev/null; then
            menuItem 'Stop VNC Server' 'killall vino-server'
        else
            menuItem 'Start VNC Server' '/usr/lib/vino/vino-server'
        fi
        menuItem 'VNC Server Preferences' 'sh -c "notify-send -t 15000 -i \"dialog-info\" \"Configure Vino\" \"In dconf-editor open:\norg -> gnome -> desktop  -> remote-access\" ;dconf-editor"'
    else
        menuItem 'Install VNC Server' "$0 --install server"
    fi

    menuEnd
fi
exit 0
