#!/bin/bash
#
#    al-lock: a wrapper for the 'light-locker-command -l' command.
#    If running in live mode, offer up a prompt detailing the live session password.
#    Else, run light-locker-command -l.
#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
#    Copyright (C) 2015-2016  John Crawley <john@archlabs.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

LOCK_COMMAND=(slimlock -l)

HELP="    al-lock a wrapper for the 'light-locker-command -l' command

Options:
    -h --help   show this message

No other options are supported.

If running in live mode, offer up a prompt detailing the live session password.
Else, run '${LOCK_COMMAND[*]}'
"
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

which ${LOCK_COMMAND[0]} >/dev/null 2>&1 || {
    echo "$0: ${LOCK_COMMAND[0]} no such command." >&2
    exit 1
}

if [ -d /lib/live ] && [ ! -f /home/$USER/.config/archlabs/al-lock ]; then
    yad --image='archlabs' --window-icon='distributor-logo-archlabs' --center --borders=20 --button=gtk-ok --fixed --on-top --title='Lock screen info:' --text='Lock screen has detected you are running a live session.\nThe username needed to unlock the screen is "user" and the password is "live".\nThis notice will only be displayed once per live session.'
    mkdir -p /home/$USER/.config/archlabs
    touch /home/$USER/.config/archlabs/al-lock
fi

"${LOCK_COMMAND[@]}"

exit 0
