#!/bin/sh

# Copyright 2016 Antonio Malcolm, released under an MPL, v. 2.0, license. All rights reserved.
#
# This file is part of Corgi Scripts (also referred to as corgi-scripts).
#
# Corgi Scripts is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# you can obtain one at http://mozilla.org/MPL/2.0/.
#
# Corgi Scripts is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either expressed or implied.
# See LICENSE.txt, for the specific language governing rights and limitations under the License,
# which should have been provided with this software, or visit http://mozilla.org/MPL/2.0/.

# corgi-openbox-menus-power-management - Generates an Openbox Pipemenu for describing and managing power management
#                                        and throttling options for various parts of the system.
#
# v2016.03.06
#
# Authored by Antonio Malcolm
#
# Requires: corgi-openbox-menus-power-management-battery.shlib
# Requires: corgi-openbox-menus-power-management-cpu.shlib
# Requires: corgi-openbox-menus-core.shlib (normally provided by corgi-openbox-menus-power-management-battery.shlib or corgi-openbox-menus-power-management-cpu.shlib)
# Requires: corgi-posix-core.shlib (normally provided by corgi-openbox-menus-power-management-battery.shlib or corgi-openbox-menus-power-management.shlib)

exitStatus=1
currentDirectory="`dirname "$0"`"
currentDirectory="`cd "$currentDirectory" ; pwd -P `"
parentDirectory="`dirname $currentDirectory`"
corgiObPowerManagementBatteryLib="$parentDirectory/lib/corgi/openbox/menus/corgi-openbox-menus-power-management-battery.shlib"
corgiObPowerManagementCpuLib="$parentDirectory/lib/corgi/openbox/menus/corgi-openbox-menus-power-management-cpu.shlib"

if [ ! -e "$corgiObPowerManagementBatteryLib" ]
then
  logger "ERROR (corgi-openbox-menus-displays): The Corgi Openbox Power Mangement Battery Menu library is missing. Exiting..."
  echo "ERROR (corgi-openbox-menus-displays): The Corgi Openbox Power Mangement Battery Menu library is missing. Exiting..."
  exit $exitStatus
fi

if [ ! -e "$corgiObPowerManagementCpuLib" ]
then
  logger "ERROR (corgi-openbox-menus-displays): The Corgi Openbox Power Mangement CPU Menu library is missing. Exiting..."
  echo "ERROR (corgi-openbox-menus-displays): The Corgi Openbox Power Mangement CPU Menu library is missing. Exiting..."
  exit $exitStatus
fi

. "$corgiObPowerManagementBatteryLib"
. "$corgiObPowerManagementCpuLib"

pipeMenu=''

batteriesMenu="`buildBatteriesDetailsMenu`"
cpusMenu="`buildCpusMenu`"

pipeMenu="`corgiObPipeMenu "content:$cpusMenu$batteriesMenu"`"
exitStatus=$?

if [ -z "$pipeMenu" ]
then
  logger "ERROR (corgi-openbox-menus-power-management): Unable to generate pipe menu. Exiting..."
  echo "ERROR (corgi-openbox-menus-power-management): Unable to generate pipe menu. Exiting..."
else
  echo "$pipeMenu"
fi

exit $exitStatus