#!/bin/sh

# Copyright 2015 Antonio Malcolm, released under an MPL, v. 2.0, license. All rights reserved.
#
# This file is part of Corgi Scripts (also referred to as corgi-scripts).
#
# Corgi Scripts is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# you can obtain one at http://mozilla.org/MPL/2.0/.
#
# Corgi Scripts is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either expressed or implied.
# See LICENSE.txt, for the specific language governing rights and limitations under the License,
# which should have been provided with this software, or visit http://mozilla.org/MPL/2.0/.

# corgi-openbox-menus-displays - Generates an Openbox menu for describing and managing X screens and display connections.
#
# v2015.06.17
#
# Authored by Antonio Malcolm
#
# Requires: corgi-openbox-menus-displays.shlib
# Requires: corgi-openbox-menus-core.shlib (normally provided by corgi-openbox-menus-displays.shlib)
# Requires: corgi-posix-core.shlib (normally provided by corgi-openbox-menus-displays.shlib)

exitStatus=1
currentDirectory="`dirname "$0"`"
currentDirectory="`cd "$currentDirectory" ; pwd -P `"
parentDirectory="`dirname $currentDirectory`"
corgiObMenusDisplaysLib="$parentDirectory/lib/corgi/openbox/menus/corgi-openbox-menus-displays.shlib"

if [ ! -e "$corgiObMenusDisplaysLib" ]
then
  logger "ERROR (corgi-openbox-menus-displays): The Corgi Openbox Displays Menu library is missing. Exiting..."
  echo "ERROR (corgi-openbox-menus-displays): The Corgi Openbox Displays Menu library is missing. Exiting..."
  exit $exitStatus
fi

. "$corgiObMenusDisplaysLib"

pipeMenu=''
pipeMenu="`buildDisplaysMenu "$@"`"
pipeMenu="`corgiObPipeMenu "content:$pipeMenu"`"
exitStatus=$?

if [ -z "$pipeMenu" ]
then
  logger "ERROR (corgi-openbox-menus-displays): Unable to generate pipe menu. Exiting..."
  echo "ERROR (corgi-openbox-menus-displays): Unable to generate pipe menu. Exiting..."
else
  echo "$pipeMenu"
fi

exit $exitStatus
