#!/bin/sh

# Copyright 2016 Antonio Malcolm, released under an MPL, v. 2.0, license. All rights reserved.
#
# This file is part of Corgi Scripts (also referred to as corgi-scripts).
#
# Corgi Scripts is subject to the terms of the Mozilla Public License, v. 2.0. 
# If a copy of the MPL was not distributed with this file, 
# you can obtain one at http://mozilla.org/MPL/2.0/.
#
# Corgi Scripts is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either expressed or implied.
# See LICENSE.txt, for the specific language governing rights and limitations under the License,
# which should have been provided with this software, or visit http://mozilla.org/MPL/2.0/.

# corgi-power-management-battery - handles management of battery status polling and the
#                                  automation of actions to be taken upon low battery status
#
# v2016.10.21
#
# Authored by Antonio Malcolm
#
# 
# Requires: corgi-power-management-battery.shlib


currentDirectory="`dirname "$0"`"
currentDirectory="`cd "$currentDirectory" ; pwd -P `"
parentDirectory="`dirname $currentDirectory`"

corgiPowerManagementBatteryLib="$parentDirectory/lib/corgi/corgi-power-management-battery.shlib"

if [ ! -e "$corgiPowerManagementBatteryLib" ]
then
  logger "ERROR (corgi-power-management-battery): $corgiPowerManagementBatteryLib is missing. Exiting..."
  echo "ERROR (corgi-power-management-battery): $corgiPowerManagementBatteryLib is missing. Exiting..."
  exit 1
fi

. "$corgiPowerManagementBatteryLib"

case "$1" in

  'polling')
  
    case "$2" in
    
      'start')
      
        shift
        shift

        pollBatteryStatus "$@"
        
      ;;
      
      'stop') pkill -f 'corgi-power-management-battery polling start' ;;
    
    esac
  
  ;;

esac

exit $?
